apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  containers:
  - image: nginx:alpine
    name: logger
    volumeMounts:
      - mountPath: "/var/www/nginx"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: log-claim
