version: "3.3"
services:
  jenkins:
    build: ./jenkins/
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "5000:5000"
    container_name: jenkins
    volumes:
      - ./jenkins/jenkins_configuration/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
